### ISSUE TITLE
miners stuck downloading

### ISSUE THREAD

**Issue by szentigrad3** [Johy/Hasher#1] opened 2018-01-03 03:38 UTC
i tried this out but when i went to benchmark it starts to download the miners then gets stuck at 91%

**Comment by fiorinin** [comment] 2018-01-03 03:46
Hi there, and thank you so much for taking some time trying it out! Sorry that you encountered a bug; I expected that a public release would make that happen, but I'm glad you reported it so that I can fix it. Can you please let me know if any miner in the following path have no executable: `C:\Users\<USER>\AppData\Roaming\Hasher\bin`? Please browse every folder in there and let me know if a `.exe` is missing in any.

Also, I'm almost done with error logging. When it will be fully implemented, you will only have to send me the log file which will be much better for debugging (e.g., if a download failed).

Thank you so much for your patience and I hope you'll be able to use it soon after I identify the issue.

**Comment by szentigrad3** [comment] 2018-01-03 04:09
yer afew of them have extracted and have files and some of them have only the 7z file

**Comment by fiorinin** [comment] 2018-01-03 04:12
Great, so I think I know where it comes from. I’ll fix that certainly tomorrow and publish a fix you’ll be able to try. Thanks again!

**Comment by szentigrad3** [comment] 2018-01-03 04:15
ok thanks

**Comment by fiorinin** [comment] 2018-01-04 01:07
Please have a new try as I think I fixed it (I can't be sure until you try since I couldn't reproduce it). Go to [the latest release](https://github.com/Johy/Hasher/releases/latest), download the `.exe`, and run it. The settings you entered yesterday should still be there unless you deleted some file in Hasher's folder, and you shouldn't have to re-download the miners you downloaded yesterday so it will be quicker.

Please let me know if this fixed the issue. If you encounter new ones, please create new tickets to keep things tidy. Thanks again and I hope this time you'll get to enjoy Hasher!

**Comment by fiorinin** [comment] 2018-01-07 23:46
Closing as I received no answer. Reopen if problem persists, thanks!

**Closed as completed by fiorinin** 2018-01-07 23:46 UTC
